services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - app-network

  todo-back:
    build:
      context: ./back
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017
    depends_on:
      - mongo
    networks:
      - app-network

  todo-front:
    build:
      context: ./front
    restart: always
    ports:
      - 80:80
    depends_on:
      - todo-back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
