Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  # database VM
  config.vm.define "database" do |database|
    database.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "database"
    end
    database.vm.network "private_network", ip: "192.168.33.20"
    database.vm.hostname = "database"
    database.vm.provision "shell", inline: <<-SHELL
      echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGmnQQRJqLt9LnvfNl+Y7oFpGXwUNDNnOwWoWfYMC0zQ' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # fileServer VM
  config.vm.define "fileServer" do |fileServer|
    fileServer.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "fileServer"
    end
    fileServer.vm.network "private_network", ip: "192.168.33.21"
    fileServer.vm.hostname = "fileServer"
    fileServer.vm.provision "shell", inline: <<-SHELL
      echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGmnQQRJqLt9LnvfNl+Y7oFpGXwUNDNnOwWoWfYMC0zQ' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # web VM
  config.vm.define "web" do |web|
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "web"
    end
    web.vm.network "private_network", ip: "192.168.33.23"
    web.vm.hostname = "web"
    web.vm.provision "shell", inline: <<-SHELL
      echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGmnQQRJqLt9LnvfNl+Y7oFpGXwUNDNnOwWoWfYMC0zQ' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

end
